### ISSUE TITLE
Individual UC diagrams in SVG

### ISSUE THREAD

**Issue by csarven** [csarven/dive-into-dokieli#1]
@rhiaro Would you mind pushing the original in SVG and if possible each UC as separate SVG?

Aside: I've used the following values in SVG for the articles, and they tend to work out well on screen as well as for LNCS and ACM prints:

```
<svg
   viewBox="0 0 640 480"
   width="100%"
   height="100%"
```

I may have mentioned this in chat:

Are there any other diagrams UC based diagrams we should include? Perhaps in reference to http://www.w3.org/TR/dpub-annotation-uc/ ?

**Comment by rhiaro** [comment]
They're not use cases, but modes of operation for dokieli, intended to illustrate the progressive nature of the features.

But sure yeah I'll make them SVG.

**Comment by rhiaro** [comment]
Blam
